name: openet
channels:
  - defaults
  - conda-forge
dependencies:
  - codecov
  - coverage
  - earthengine-api>=0.1.204
  - gdal
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - pip
  - pytest>=4.3.0
  - pytest-cov
  - pytest-runner
  - python=3.6
  - python-dateutil
  - pip:
    - openet-core
